repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        files: (substratest|tests|ci)/.+\.py
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]
        files: (substratest|tests|ci)/.+\.py

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: (substratest|tests|ci)/.+\.py
