[tool.black]
line-length = 120
target-version = ['py36']

[tool.isort]
filter_files = true
force_single_line = true
line_length = 120
profile = "black"
src_paths = ["substratest", "tests"]

[tool.towncrier]
directory = "changes"
filename = "CHANGELOG.md"
start_string = "<!-- towncrier release notes start -->\n"
underlines = ["", "", ""]
title_format = "## [{version}](https://github.com/Substra/substra-tests/releases/tag/{version}) - {project_date}"
[tool.towncrier.fragment.added]
[tool.towncrier.fragment.removed]
[tool.towncrier.fragment.changed]
[tool.towncrier.fragment.fixed]
