apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: substrafoundation/connect-tests
      context: .
      docker:
        dockerfile: docker/substra-tests/Dockerfile
deploy:
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
      - name: connect-tests
        chartPath: charts/connect-tests
        namespace: connect-tests
        imageStrategy:
          helm: {}
        values:
          image: substrafoundation/connect-tests
    flags:
      install: ["--create-namespace"]

