---
steps:
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo -n "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    args:
      - "clone"
      - "git@github.com:${_GIT_REPOSITORY}"
      - "--branch=${_BRANCH}"
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git clone ${_SUBSTRA_GIT_REPO}
        cd substra
        git checkout ${_SUBSTRA_GIT_COMMIT}
        cd ..
        git clone ${_CONNECTTOOLS_GIT_REPO}
        cd connect-tools
        git checkout ${_CONNECTTOOLS_GIT_COMMIT}
        cd ..
    volumes:
      - name: "ssh"
        path: "/root/.ssh"

  - name: "gcr.io/kaniko-project/executor:v1.3.0"
    args:
      - --destination=eu.gcr.io/$PROJECT_ID/${_IMAGE}:ci-${_COMMIT}-${_SUBSTRA_GIT_COMMIT}-${_CONNECTTOOLS_GIT_COMMIT}
      - --cache=${_KANIKO_CACHE_ENABLED}
      - --dockerfile=connectlib/docker/connectlib-tests/Dockerfile
      - --context=./
      - --cache-ttl=${_KANIKO_CACHE_TTL}

tags:
  - ${_BUILD_TAG}
# In the CI, these substitutions are overwritten by `ci.build_images`
substitutions:
  _BUILD_TAG: "connectlib"
  _IMAGE: "connectlib"
  _GIT_REPOSITORY: "owkin/connectlib.git"
  _BRANCH: "main"
  _COMMIT: "HEAD"
  _KANIKO_CACHE_ENABLED: "true"
  _KANIKO_CACHE_TTL: "168h"
  _SSH_KEY_SECRET: "projects/602744764353/secrets/connect-e2e-deploy-key/versions/3"
  _SUBSTRA_GIT_REPO: "git@github.com:owkin/substra.git"
  _SUBSTRA_GIT_COMMIT: "master"
  _CONNECTTOOLS_GIT_REPO: "git@github.com:owkin/connect-tools.git"
  _CONNECTTOOLS_GIT_COMMIT: "master"

timeout: 1200s
availableSecrets:
  secretManager:
    - versionName: ${_SSH_KEY_SECRET}
      env: "SSH_KEY"
