steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/SubstraFoundation/hlf-k8s.git', '--depth', '1', '--branch', '${_BRANCH}']
- name: 'gcr.io/kaniko-project/executor:v1.0.0'
  args:
  - --destination=eu.gcr.io/$PROJECT_ID/fabric-peer:ci-${_COMMIT}
  - --cache=true
  - --dockerfile=hlf-k8s/images/fabric-peer/Dockerfile
  - --context=hlf-k8s
  - --cache-ttl=${_KANIKO_CACHE_TTL}
tags:
- ${_BUILD_TAG}
substitutions:
    _BUILD_TAG: "substra-tests"
    _COMMIT: "HEAD"
    _BRANCH: "master"
    _KANIKO_CACHE_TTL: "168h"
timeout: 1200s
