---
steps:
  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo -n "$$SSH_KEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    args:
      - "clone"
      - "git@github.com:${_GIT_REPOSITORY}"
      - "tests"
      - "--depth=1"
      - "--branch=${_BRANCH}"
    volumes:
      - name: "ssh"
        path: /root/.ssh

  # We should checkout the correct thing
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git clone ${_SUBSTRA_GIT_REPO}
        cd substra
        git checkout ${_SUBSTRA_GIT_COMMIT}
        cd ..
        cp -r substra tests/substra
    volumes:
      - name: "ssh"
        path: "/root/.ssh"

  - name: "gcr.io/kaniko-project/executor:v1.3.0"
    args:
      - --destination=eu.gcr.io/$PROJECT_ID/${_IMAGE}:ci-${_COMMIT}-${_SUBSTRA_GIT_COMMIT}
      - --cache=true
      - --dockerfile=tests/docker/substra-tests/Dockerfile
      - --context=tests
      - --cache-ttl=${_KANIKO_CACHE_TTL}

tags:
  - ${_BUILD_TAG}
substitutions:
  _BUILD_TAG: "connect-tests"
  _IMAGE: "connect-tests"
  _COMMIT: "HEAD"
  _BRANCH: "master"
  _SUBSTRA_GIT_REPO: "git@github.com:owkin/substra.git"
  _SUBSTRA_GIT_COMMIT: "master"
  _KANIKO_CACHE_TTL: "168h"
  _GIT_REPOSITORY: "SubstraFoundation/substra-tests.git"
  _SSH_KEY_SECRET: "projects/602744764353/secrets/connect-e2e-deploy-key/versions/3"
timeout: 1200s
availableSecrets:
  secretManager:
    - versionName: ${_SSH_KEY_SECRET}
      env: "SSH_KEY"
