apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: [
        "--dockerfile",
        "docker/substra-backend/Dockerfile",
        "--context",
        "git://github.com/SubstraFoundation/substra-backend.git",
        "--no-push"
        # "--destination",
        # "<gcr.io/$PROJECT/$IMAGE:$TAG>"
    ]
    # volumeMounts:
    #   - name: kaniko-secret
    #     mountPath: /secret
    # env:
    #   - name: GOOGLE_APPLICATION_CREDENTIALS
    #     value: /secret/kaniko-secret.json
  restartPolicy: Never
  # volumes:
  #   - name: kaniko-secret
  #     secret:
  #       secretName: kaniko-secret
