apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "substra-tests-stack.fullname" . }}
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.serviceAccount}}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bash", "-c"]
          args:
            - |
              ./deploy.sh {{ .Values.deploy.defaultRepo }}
      restartPolicy: Never