name: Deploy GCP cleaning function

on:
  push:
    branches:
      - "master"
    paths:
      - "ci/cloudbuild/deploy_cloud_function.yaml"
      - "ci/cluster_cleaning_function/**"

env:
  GCP_PROJECT: "connect-314908"
  GCP_SERVICE_ACCOUNT: "e2e-tests@connect-314908.iam.gserviceaccount.com"
  GCP_SERVICE_ACCOUNT_KEY: "ci/keys/connect-314908-3902714646d9.json.gpg"
  GCP_SSH_SECRET: "projects/101637030044/secrets/connect-e2e-deploy-key/versions/2"

jobs:
  deploy:
    name: Deploy function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout connect-tests
        uses: actions/checkout@v2
      - name: Open GCP key
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --output ./ci/keys/gcp_sa_key.json "${GCP_SERVICE_ACCOUNT_KEY}"
      - name: Deploy function
        run: |
          gcloud auth activate-service-account "${GCP_SERVICE_ACCOUNT}" --key-file=./ci/keys/gcp_sa_key.json

          gcloud builds submit ci/cloudbuild/known_host.tgz \
            --config=ci/cloudbuild/deploy_cloud_function.yaml \
            --project="${GCP_PROJECT}" \
            --async \
            --format json \
            --substitutions="_BRANCH=master,_GIT_REPOSITORY=${GITHUB_REPOSITORY}.git,_SSH_KEY_SECRET=${GCP_SSH_SECRET}" \
            | jq -r .id > build_id

          while gcloud builds describe $(cat build_id) --project="${GCP_PROJECT}" --format json | jq -r .status | grep -q -e "WORKING" -e "QUEUED"
          do
            echo "Build in progress"
            sleep 10
          done

          if [ "$(gcloud builds describe $(cat build_id) --project="${GCP_PROJECT}" --format json | jq -r .status)" != "SUCCESS" ]; then
            echo "The Build failed"
            exit 1
          fi
          echo "The Build succeeded"
