name: Python

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: test-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: ["3.8", "3.9", "3.10", "3.11"]
    env:
      SUBSTRA_REF: main
      TOOLS_REF: main
      SRC_DIRS: substratest tests ci

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: checkout substra
        uses: actions/checkout@v4
        with:
          repository: Substra/substra
          path: substra
          ref: ${{ env.SUBSTRA_REF }}

      - name: checkout substra tools
        uses: actions/checkout@v4
        with:
          repository: Substra/substra-tools
          path: substra-tools
          ref: ${{ env.TOOLS_REF }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tools
        run: pip install -r <(egrep "flake|black|isort" requirements.txt)

      - name: Check formatting - Black
        run: |
          black --check --diff $SRC_DIRS

      - name: Check formatting - isort
        run: |
          isort --check $SRC_DIRS

      - name: Lint
        run: flake8 $SRC_DIRS

      - name: Install requirements
        run: |
          pip install --no-cache-dir ./substra-tools
          pip install --no-cache-dir ./substra
          pip install --no-cache-dir -r requirements.txt
          pip install -r requirements-workflows.txt

      - name: Test
        run: |
          make test-local
