name: Python

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "12 3 * * 2-6" # every Tuesday to Saturday at 3:12 AM

env:
  GCP_SERVICE_ACCOUNT: "e2e-tests@connect-314908.iam.gserviceaccount.com"
  GCP_SERVICE_ACCOUNT_KEY: "keys/connect-314908-3902714646d9.json.gpg"

jobs:
  test:
    name: test-py-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: ["3.8", "3.9"]
    env:
      SUBSTRA_REF: main
      TOOLS_REF: main
      SRC_DIRS: substratest tests ci

    steps:
      - name: checkout connect-tests
        uses: actions/checkout@v2

      - name: checkout connect SDK
        uses: actions/checkout@v2
        with:
          repository: owkin/substra
          path: substra
          token: ${{ secrets.OWLFRED_PAT }}
          ref: ${{ env.SUBSTRA_REF }}

      - name: checkout substra tools
        uses: actions/checkout@v2
        with:
          repository: owkin/connect-tools
          path: substra-tools
          token: ${{ secrets.OWLFRED_PAT }}
          ref: ${{ env.TOOLS_REF }}

      - name: Open GCP key
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --output ./keys/gcp_sa_key.json "${GCP_SERVICE_ACCOUNT_KEY}"

      - name: Docker login
        run: |
          gcloud auth activate-service-account "${GCP_SERVICE_ACCOUNT}" --key-file=./keys/gcp_sa_key.json
          gcloud auth configure-docker 'gcr.io'

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tools
        run: pip install -r <(egrep "flake|black|isort" requirements.txt)

      - name: Check formatting - Black
        run: |
          black --check --diff $SRC_DIRS

      - name: Check formatting - isort
        run: |
          isort --check $SRC_DIRS

      - name: Lint
        run: flake8 $SRC_DIRS

      - name: Install requirements
        run: |
          pip install --no-cache-dir ./substra-tools
          pip install --no-cache-dir ./substra
          pip install --no-cache-dir -r requirements.txt
          pip install -r requirements-workflows.txt
      - name: Test
        run: |
          start=`date +%s`
          python -u ./run-local-test.py \
            --write-summary-to-file ./.slack_message
          end=`date +%s`
          echo "LOCAL_TESTS_DURATION_SECONDS=$((end-start))" >> $GITHUB_ENV

      - if: always() && github.event_name == 'schedule'
        name: Send Slack report
        run: |
          ./send-slack-report.py '${{ secrets.SLACK_WEBHOOK }}' .slack_message \
          --title 'SDK local tests' \
          --status '${{ job.status }}' \
          --link 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
          --duration-seconds "${LOCAL_TESTS_DURATION_SECONDS}"
